[package]
name = "sudoku"
version = "0.1.0"
authors = ["Zachary Kohnen <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
cairo-rs = "0.9"
derive_more = "0.99"
gdk = "0.13"
gio = "0.9"
glib = "0.10"
gtk = { version = "0.9", features = ["v3_16"] }
thiserror = "1.0"